Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -9,28 +9,28 @@ jobs:
       - name: Branch checks
         run: |
           case $GITHUB_HEAD_REF in
-          feature/*)
-              if [[ ! ( "$GITHUB_BASE_REF" == "develop" ) ]]; 
-              then 
-                  echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
+              feature/*)
+                  if [[ ! ( "$GITHUB_BASE_REF" == "develop" ) ]]; 
+                  then 
+                      echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
+                      exit 2
+                  fi
+              ;;
+              release/*)
+                  if [[ ! ( "$GITHUB_BASE_REF" == "develop" || "$GITHUB_BASE_REF" == "main" ) ]]; 
+                  then 
+                      echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
+                      exit 2
+                  fi
+              ;;
+              hotfix/*)
+                  if [[ ! ( "$GITHUB_BASE_REF" == "develop" || "$GITHUB_BASE_REF" == "main" ) ]]; 
+                  then 
+                      echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
+                      exit 2
+                  fi
+              ;;
+              *)
+                  echo "The branch $GITHUB_HEAD_REF cannot be merged to the branch $GITHUB_BASE_REF "
                   exit 2
-              fi
-          ;;
-          release/*)
-              if [[ ! ( "$GITHUB_BASE_REF" == "develop" || "$GITHUB_BASE_REF" == "main" ) ]]; 
-              then 
-                  echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
-                  exit 2
-              fi
-          ;;
-          hotfix/*)
-              if [[ ! ( "$GITHUB_BASE_REF" == "develop" || "$GITHUB_BASE_REF" == "main" ) ]]; 
-              then 
-                  echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
-                  exit 2
-              fi
-          ;;
-          *)
-              echo "The branch $GITHUB_HEAD_REF cannot be merged to the branch $GITHUB_BASE_REF "
-              exit 2
           esac
